const content = document.querySelector('#content');
const steps = [
  ['api', 'Подключаем нейросеть', 'Получим первый ответ.'],
  ['preset', 'Ставим пресет', 'Выберем инструкции для нашей истории.'],
  ['persona', 'Создаём свою роль', 'Расскажем, за кого играем.'],
  ['character', 'Добавляем персонажа', 'Загрузим карточку собеседника.'],
  ['chat', 'Начинаем общаться', 'Напишем и освоим основные кнопки.']
];
const shot = (file, caption) => `<figure class="screenshot"><button class="image-button" data-image="assets/${file}" aria-label="Увеличить: ${caption}"><img src="assets/${file}" alt="${caption}" loading="lazy"></button><figcaption>${caption} · Нажми на картинку, чтобы увеличить.</figcaption></figure>`;
const note = (text, warn = false) => `<div class="callout${warn ? ' warning' : ''}">${text}</div>`;
const link = (url, text) => `<a href="${url}">${text} ↗</a>`;
const next = (url, text) => `<div class="next"><a href="#home">На главную</a><a class="btn" href="${url}">${text} →</a></div>`;
const command = text => `<pre><code>${text}</code></pre><button class="copy" data-copy>Скопировать команду</button>`;
function home() {
  return `<div class="wrap"><section class="hero"><div><div class="eyebrow">SillyTavern · гайд для новичков</div><h1>Твоя история<br>начинается<br><em>в Таверне.</em></h1><p>Привет, я Шиппис! Помогу тебе открыть Таверну, настроить её и начать общаться с персонажами.</p><p>Всё по шагам: куда нажать, что заполнить и как понять, что получилось.</p><div class="actions"><a class="btn" href="#install">Начнём с установки</a><a href="#setup">Таверна уже открывается</a></div><span class="small">Можно идти в своём темпе и возвращаться к любому шагу.</span></div><figure class="welcome-art"><img src="assets/author-schippis.jpg" alt="Шиппис с волшебным пером"><figcaption>У каждой истории есть начало</figcaption></figure></section><section><div class="section-head"><h2>От запуска до первого диалога</h2><span class="small">Шесть небольших шагов</span></div><div class="cards"><a class="card" href="#install"><span class="step-no">01</span><h3>Открываем Таверну ↗</h3><p>На своём устройстве или через хостинг — с любого устройства.</p></a>${steps.map(([id,title,desc],i)=>`<a class="card" href="#setup/${id}"><span class="step-no">0${i+2}</span><h3>${title} ↗</h3><p>${desc}</p></a>`).join('')}</div><p class="site-updates">Сайт будет обновляться: здесь появятся новые гайды, рекомендации и авторы. Заглядывай ещё!</p></section></div>`;
}
const installation = getInstallations();
function install(platform='windows') { if(!installation[platform]) platform='windows'; return `<div class="wrap"><div class="page-title"><div class="eyebrow">Шаг 1 / Установка Таверны</div><h1>Сначала откроем Таверну.</h1><p>Выбери, как тебе удобнее: на своём устройстве или через хостинг. Через хостинг можно пользоваться Таверной с любого устройства с современным браузером.</p></div><div class="platforms">${[['windows','Windows'],['android','Android'],['mac','macOS'],['linux','Linux'],['hosting','Хостинг']].map(([id,title])=>`<a href="#install/${id}" ${id===platform?'aria-current="page"':''}>${title}</a>`).join('')}</div><article class="article">${platform!=='hosting'?note('Хочешь открыть Таверну без установки или пользоваться с любого устройства? <a href="#install/hosting">Выбери хостинг →</a>'):''}${installation[platform]}${platform!=='hosting'?`<details><summary>Можно открыть эту Таверну с телефона или другого устройства?</summary><p>Да. Дома можно подключиться к Таверне на компьютере с телефона, если оба устройства находятся в одной Wi-Fi-сети. Нужно разрешить сетевой доступ в настройках Таверны; компьютер должен оставаться включённым, а Таверна — запущенной. Для установки на Android принцип тот же: устройство с Таверной должно продолжать работать.</p><p>На другом устройстве используют локальный адрес устройства с Таверной, а не localhost. Это отдельная настройка — установка по нашему гайду сама по себе не открывает доступ по сети.</p><p>Для доступа вне дома потребуется настроить защищённый удалённый доступ, например через VPN между своими устройствами. Другой вариант — арендовать личный сервер и установить Таверну на нём. Покупать сервер для доступа внутри домашней сети не нужно.</p><p>Если не хочется разбираться с сетью и сервером, проще <a href="#install/hosting">выбрать готовый хостинг</a>.</p></details>`:''}${platform!=='hosting'&&platform!=='other'?note('Выполняй команды по одной. Если команда завершилась ошибкой, остановись и сохрани её текст — не переходи к следующей. Перед обновлением полезно сохранить копии папки <code>data</code> и файла <code>config.yaml</code> из папки SillyTavern.'):''}${next('#setup','Таверна открылась — настроим её')}</article></div>`; }
const lessons = {
  api: getConnectionGuide(),
  preset: `<h2>Ставим пресет</h2><p><b>Пресет</b> — готовый набор настроек для нейросети. В нём собраны инструкции для нейросети и настройки её ответов.</p><p>Автор пресета собирает инструкции в отдельные блоки. Рядом с ними есть переключатели: их часто называют <b>тогглами</b>. Включённый блок участвует в подготовке запроса, выключенный — не отправляется.</p><h2>Зачем нужны тогглы</h2><p>В зависимости от пресета они могут задавать:</p><ul><li><b>Язык и стиль:</b> например, русский язык, подробные описания или больше диалогов.</li><li><b>Поведение персонажа:</b> следовать своей роли и не писать действия за пользователя.</li><li><b>Подачу истории:</b> темп сцены, настроение и формат повествования.</li><li><b>Оформление ответа:</b> как выделять речь, мысли и действия.</li></ul><p>Названия и возможности зависят от автора. Не каждый блок — дополнительное правило: в списке также могут быть описание персонажа, персона и история чата.</p><h2>Как импортировать</h2><ol><li>Скачай файл пресета по ссылке автора. Проверь, что он подходит для твоей модели и <b>Chat Completion</b>.</li><li>Нажми значок <b>ползунков</b> в верхней панели — откроются настройки ответа.</li><li>Найди кнопку импорта рядом со списком пресетов. На компьютере наведи на значок курсор, чтобы прочитать подсказку. Нажми и выбери скачанный файл.</li><li>Убедись, что в списке появилось и выбрано название твоего пресета.</li></ol>${shot("preset.jpg","Выбор пресета, размер контекста и максимальная длина ответа")}<h2>Как выбрать инструкции</h2><ol><li>Прокрути эту же панель ниже, к разделу <b>«Промпты»</b>.</li><li>Прочитай рекомендации автора: какие блоки обязательны, а какие выбираются по вкусу. Иногда из нескольких вариантов нужно включить только один.</li><li>Для начала оставь предложенный автором набор. Не включай все тогглы сразу: инструкции могут противоречить друг другу.</li><li>Чтобы узнать, что делает блок, открой его через карандаш. Если меняешь текст, сохрани его в редакторе, а затем сохрани сам пресет кнопкой сохранения рядом с его названием.</li></ol>${note("Если инструкции уже входят в пресет, отдельно вставлять тот же промпт ещё раз не нужно.")}<h2>Не выставляй контекст на максимум</h2><p><b>Контекст</b> — текст, который Таверна передаёт нейросети перед ответом: инструкции, сведения о персонаже и переписка. Его объём измеряется в токенах — небольших фрагментах текста.</p><p>Оставь «Неограниченный размер контекста» выключенным. Эта галочка снимает ограничение ползунка, но не увеличивает возможности модели. Слишком большой запрос может быть дороже, медленнее или закончиться ошибкой.</p><p><b>Максимальная длина ответа</b> — сколько токенов разрешено сгенерировать в одном ответе. Это тоже не нужно выставлять на максимум.</p><p>Числа на картинке показывают расположение настроек. Значения для себя выбирай по ограничениям модели, сервиса и рекомендациям автора пресета.</p>${renderPresetPicks()}`,
  persona: `<h2>Кем ты будешь в этой истории?</h2><p><b>Персона</b> — твоя роль. Это может быть придуманный герой: настоящие имя и биография не нужны. Карточку собеседника мы добавим следующим шагом.</p><ol><li>Нажми на значок лица в верхней панели — откроется «Управление персоной».</li><li>Нажми «Создать» и задай имя. При желании добавь аватар.</li><li>Заполни «Описание персоны»: несколько фактов о твоём герое.</li><li>Выбери персону в списке и проверь, что справа под «Текущая персона» показано нужное имя.</li></ol>${shot('persona.jpg','Управление персоной: создание слева, имя и описание справа')}<h2>Что написать в описании</h2><div class="example">{{user}} — Маттео, 23 года, рост 193 см, плечистый. Развитая мускулатура. Прическа маллет, косая приподнятая челка на левую сторону. Цвет волос: крашеные в фиолетовые. Узкие глаза серого цвета, хмурые брови, красивое тонкое лицо с небольшим носом, острыми скулами и пухлыми губами. Пирсинг на языке, нижней губе и брови, множественные проколы в ушах. Мастер тату.</div><p class="small">Можно скопировать идею и заменить детали на свои. Длинная биография для первого чата не нужна.</p><p><b>Чтобы сэкономить токены, можно перевести описание на английский.</b> У многих моделей оно получится компактнее в токенах, но это зависит от модели и текста. Саму ролевую игру при этом можно вести на русском.</p>${note('<b>Получилось, если:</b> нужная персона выбрана и её описание заполнено. Для первого знакомства остальные параметры можно оставить как есть.')}<details><summary>А что значит {{user}} на скриншоте?</summary><p>Это обозначение, вместо которого Таверна подставляет имя пользователя. В примере выше {{user}} заменится именем выбранной персоны.</p></details>`,
  character: characterGuide(),
  chat: '<h2>Теперь можно играть</h2><p>Прочитай приветствие персонажа, напиши ответ от имени своей персоны и нажми кнопку отправки справа внизу.</p>' + shot('chat.jpg','Чат: поле сообщения и кнопка отправки') + revisedChatMenus() + note('Если на твою реплику пришёл новый ответ, базовая настройка работает. Можно продолжать историю.')
};
lessons.preset += toggleGuide();
function setup(id='api') { if(['lorebooks','user-settings'].includes(id)) return extraGuide(id); if(!lessons[id]) id='api'; const index=steps.findIndex(s=>s[0]===id); return `<div class="wrap"><div class="page-title"><div class="eyebrow">Шаг ${index+2} из 6 / Настройка Таверны</div><h1>${steps[index][1]}.</h1></div><div class="layout"><aside class="sidebar" aria-label="Шаги настройки"><div class="small">ИДЁМ ПО ПОРЯДКУ</div>${steps.map(([key,title],i)=>`<a href="#setup/${key}" ${id===key?'aria-current="step"':''}>${i+2}. ${title}</a>`).join('')}<div class="small">ДОПОЛНИТЕЛЬНО</div><a href="#setup/lorebooks">Лорбуки</a><a href="#setup/user-settings">Настройки пользователя</a></aside><article class="article">${lessons[id]}${next(index<4?'#setup/'+steps[index+1][0]:'#extensions',index<4?steps[index+1][1]:'Посмотреть расширения')}</article></div></div>`; }
function extensions() { return renderExtensionsCollection(); }
function bots() { return renderAuthorGallery(); }
function render() {
  const [page='home',sub] = location.hash.slice(1).split('/');
  const views={home,install:()=>install(sub),setup:()=>setup(sub),extensions,bots};
  const active=views[page]?page:'home';
  document.body.dataset.page=active;
  content.innerHTML=views[active]().replace(/>([^<]*)</g, (_, text) => '>' + text.replace(/[↗→✦✧]/g, symbol => symbol === '↗' ? '<span class="ui-arrow diagonal" aria-hidden="true"></span>' : symbol === '→' ? '<span class="ui-arrow" aria-hidden="true"></span>' : '<span class="ui-star" aria-hidden="true"></span>') + '<');
  document.querySelectorAll('header nav a').forEach(a=>{if(a.hash==='#'+active)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current');});
  document.title=({home:'Таверна с Шиппис — начинаем вместе',install:'Установка Таверны',setup:'Настройка Таверны',extensions:'Расширения',bots:'Боты и авторы'})[active];
  window.scrollTo(0,0);
}
window.addEventListener('hashchange',()=>{render();content.focus({preventScroll:true});});
const dialog=document.querySelector('#image-dialog');
document.addEventListener('click',async event=>{
  const jump=event.target.closest('[data-jump]');
  if(jump) document.getElementById(jump.dataset.jump)?.scrollIntoView({block:'start'});
  const image=event.target.closest('[data-image]');
  if(image){dialog.querySelector('img').src=image.dataset.image;dialog.querySelector('img').alt=image.querySelector('img').alt;dialog.querySelector('p').textContent=image.querySelector('img').alt;dialog.showModal();}
  if(event.target.closest('.close') || event.target===dialog)dialog.close();
  const copy=event.target.closest('[data-copy]');
  if(copy){const text=copy.previousElementSibling.textContent;try{await navigator.clipboard.writeText(text);copy.textContent='Скопировано';}catch{const selection=window.getSelection();const range=document.createRange();range.selectNodeContents(copy.previousElementSibling);selection.removeAllRanges();selection.addRange(range);copy.textContent='Текст выделен — нажми Ctrl+C';}}
});
render();



