const extensionPicks = [
 ['MemoryBook','Гайд: Плачу над глупой таверной','Память','Помогает сохранять события истории в записях памяти. По ссылке — гайд по настройке и промпты.','https://t.me/sillykamoi/153'],
 ['Трекер памяти','smokyPab','Память','Выделяет факты о персонажах, событиях и секретах и добавляет их в запрос компактным блоком. Факты можно редактировать.','https://t.me/smokshipub/15'],
 ['Love Score','Сора','История и отношения','Отслеживание отношений с персонажем: изменение симпатии, разные режимы и развитие связи по ходу истории.','https://t.me/sorathem/918'],
 ['Случайные события','Кошка в Таверне','История и отношения','Кнопки для сюжетного поворота, драмы или случайного события. Выбираешь вариант — он добавляется к следующему ответу.','https://github.com/delidgi/silly-tavern-auto-event-buttons.git'],
 ['Ивенты','Кошка в Таверне','История и отношения','Подбрасывает события автоматически. Можно выбрать категории, настроить шанс и добавить собственные идеи.','https://github.com/delidgi/ST-extension-chaos-events'],
 ['Телефон','Кошка в Таверне','История и отношения','Телефон для твоей персоны: можно писать посты, пользоваться приложениями и делать покупки внутри ролевой истории.','https://github.com/Delidgi-meow/Phone-ST'],
 ['NOVA','Кадис','История и отношения','Соцсеть вокруг истории: посты персонажей, личные сообщения, отношения и фотографии. События связываются с основным чатом.','https://github.com/ann22cadis/NOVA'],
 ['Slay Images','Wewwa','Картинки и удобство','Дополнение для работы с изображениями в Таверне. Подробности и настройки — в посте автора.','https://t.me/wewwajai/1143'],
 ['Start Page','Мунси','Картинки и удобство','Упорядочивает стартовую страницу: виды списка чатов, поиск, фильтры по персонажам, теги и заметки.','https://github.com/moonnsy/startpage'],
 ['Мудборд','Мунси','Картинки и удобство','Собирай картинки, цитаты, заметки и стикеры, рисуй и строй деревья отношений. Доску можно отправить боту, чтобы получить его реакцию.','https://github.com/moonnsy/MoodBoard'],
 ['LOOM','Кадис','Для создателей','Создавай карточки и лорбуки вместе с нейросетью: оценивай абзацы от 0 до 10, оставляй замечания и получай переработанный текст.','https://github.com/ann22cadis/LOOM-extension'],
 ['Фетиш-менеджер','Кошка в Таверне','Для взрослых историй','Настройка предпочтений взрослых персонажей: выбор пунктов, интенсивности и вероятности их появления в истории.','https://github.com/delidgi/fetish-manager'],
 ['Беременность и цикл','Кошка в Таверне','Для взрослых историй','Добавляет в ролевую историю отслеживание цикла и беременности персонажей. Это игровая механика, а не медицинский инструмент.','https://github.com/delidgi/Pregnancy-and-menstruation']
];
function renderExtensionsCollection(){
 const groups=[...new Set(extensionPicks.map(x=>x[2]))];
 const cards=group=>extensionPicks.filter(x=>x[2]===group).map(([name,by,,desc,url])=>`<article class="recommend-card"><span class="card-gem" aria-hidden="true">✧</span><p class="byline">${by}</p><h3>${name}</h3><p>${desc}</p><a class="source-link" href="${url}" target="_blank" rel="noopener noreferrer">${name==='MemoryBook'?'Гайд по настройке':url.includes('t.me')?'Пост автора':'Страница расширения'} ↗</a></article>`).join('');
 return `<div class="wrap collection-page"><div class="page-title"><div class="eyebrow">Маленькие дополнения к большим историям</div><h1>Интересные расширения.</h1><p>Память, картинки, неожиданные события и новые способы играть. Выбирай то, чего не хватает именно твоей истории.</p></div><details><summary>Как установить расширение?</summary><p>Открой кубики в верхней панели → «Установить расширение». Для установки нужна ссылка на репозиторий GitHub. Если здесь дана ссылка на Telegram, сначала открой пост автора и найди в нём ссылку установки.</p>${shot('extensions.png','Панель расширений')}</details><div class="collection-jumps">${groups.map((g,i)=>`<button data-jump="collection-${i}">${g}</button>`).join('')}</div>${groups.map((g,i)=>`<section class="collection-section" id="collection-${i}"><h2><span aria-hidden="true">✦</span> ${g}</h2><div class="recommend-grid">${cards(g)}</div></section>`).join('')}<p class="small">Некоторые дополнения используют дополнительные запросы к нейросети или сервис изображений. Условия подключения смотри у автора.</p>${next('#setup/chat','Вернуться к чату')}</div>`;
}
function renderPresetPicks(){
 const groups=[['Gemini',[['NoriMyn','https://t.me/MoriNori_hi/367'],['Шино','https://t.me/ah_ah_shino4ka/1755']]],['GPT',[['NoriMyn','https://t.me/MoriNori_hi/341']]],['Claude',[['NoriMyn','https://t.me/MoriNori_hi/367'],['Плачу над глупой таверной','https://nufahi.github.io/nesquik-duo/']]],['DeepSeek',[['Гайды от Макса','https://t.me/btwiusesillytavern/128']]]];
 return `<h2>Выбираем пресет под модель</h2><p>Открой материал автора и выбери файл для своей модели. Там же смотри пояснения к тогглам и обновления.</p><div class="recommend-grid preset-picks">${groups.map(([name,links])=>`<section class="recommend-card"><span class="card-gem" aria-hidden="true">✧</span><p class="byline">Пресеты для</p><h3>${name}</h3><ul>${links.map(([author,url])=>`<li><a href="${url}" target="_blank" rel="noopener noreferrer">${author} ↗</a></li>`).join('')}</ul></section>`).join('')}</div>`;
}
function renderProviderPicks(){
 return `<h2>Где получить ключ и адрес</h2><p>Перед покупкой загляни в сообщество провайдера: посмотри свежие сообщения о стабильности, доступности нужной модели и пополнении баланса.</p><div class="recommend-grid"><article class="recommend-card"><p class="byline">API-провайдер</p><h3>Роутми</h3><p><a href="https://rout.my/" target="_blank" rel="noopener noreferrer">Сайт ↗</a></p><a href="https://discord.gg/J32qJAzEa" target="_blank" rel="noopener noreferrer">Сообщество в Discord ↗</a></article><article class="recommend-card"><p class="byline">API-провайдер</p><h3>Линкапи</h3><p><a href="https://linkapi.ai/" target="_blank" rel="noopener noreferrer">Сайт ↗</a></p><a href="https://discord.gg/kanonmama" target="_blank" rel="noopener noreferrer">Discord для пополнения ↗</a></article></div>`;
}

