// Author artwork and original channels.
const authorProfiles = [
 {id:'schippis',name:'Schippis',initial:'S',image:'assets/author-schippis.jpg',url:'https://t.me/schippisschreibt',description:'Ваша верная слуга. Пишу ботов на разные темы — одиночек и мульти, а ещё промпты для картинок.'},
 {id:'avtobus',name:'Автобус',initial:'А',image:'assets/authot-avtobus.jpg',url:'https://t.me/avtobusbots',description:'Автор ботов для ролевых историй. Знакомься с персонажами в Telegram-канале.'},
 {id:'murx',name:'múrx',initial:'m',image:'assets/author-murx.jpg',url:'https://t.me/murxaibot',description:'Пишет ботов и создаёт темы для Таверны и Tavo.'},
 {id:'anfitka',name:'Anfitka',initial:'A',image:'assets/author-anfitka.jpg',url:'https://t.me/anfitka',description:'Карточки персонажей и публикации автора — в Telegram-канале.'},
 {id:'mommyrat',name:'Mommy Rat ST•J.ai',initial:'M',image:'assets/author-mommyrat.jpg',url:'https://t.me/mommy_rat_st_jai',description:'Карточки персонажей и публикации автора — в Telegram-канале.'},
 {id:'wewwa',name:'Wewwa',initial:'W',image:'assets/author-wewwa.jpg',url:'https://t.me/wewwajai',description:'Пишет ботов и гайды по Таверне. Автор Slay Images — расширения для генерации изображений.'}
];
function renderAuthorGallery(){return `<div class="wrap author-gallery"><div class="issue-line"><span>Лица наших историй</span><span>Авторы / персонажи</span></div><div class="gallery-heading"><p class="eyebrow">Боты и авторы</p><h1>Те, кто создают <em>целые миры.</em></h1><p>Знакомься с авторами и находи истории, в которые хочется вернуться.</p></div><div class="author-grid">${authorProfiles.map((a,i)=>`<article class="author-card ${a.id}"><div class="author-art">${a.image?`<img src="${a.image}" alt="Иллюстрация автора ${a.name}">`:`<div class="author-art-placeholder"><span class="author-initial" aria-hidden="true">${a.initial}</span><span class="art-label">Место для иллюстрации автора</span></div>`}<span class="author-index">0${i+1}</span><span class="author-star" aria-hidden="true">✧</span></div><div class="author-info"><p class="eyebrow">Автор персонажей</p><h2>${a.name}</h2><p>${a.description||'Здесь появятся знакомство с автором и его персонажи.'}</p>${a.url?`<a class="author-link" href="${a.url}" target="_blank" rel="noopener noreferrer">К автору ↗</a>`:'<span class="author-link pending-link">Ссылка на автора скоро появится</span>'}</div></article>`).join('')}</div><section class="finder-recommendation"><p>Проект — <a href="https://t.me/rpcards_finder_bot" target="_blank" rel="noopener noreferrer">«АИ Дайвинчик»</a>: Telegram-бот, где можно искать карточки по тегам и категориям, сохранять понравившихся персонажей и предлагать свои работы.</p></section><div class="gallery-bottom"><span aria-hidden="true">✦</span><div><h2>Персонаж уже выбран?</h2><p>Покажу, как загрузить его карточку в Таверну.</p></div><a class="btn" href="#setup/character">Добавить персонажа ↗</a></div></div>`;}
